[build]
  publish = "public/"
  command = "hugo"
[build.environment]
  HUGO_VERSION = "0.150.0"
[context.production]
  branch = "main"
[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  prettify_urls = true
[build.processing.images]
  compress = true
